# Generated by Django 6.0.3 on 2026-04-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_season_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='current_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
