# Generated by Django 6.0.3 on 2026-04-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_player_injury_days_player_injury_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_cap', models.BigIntegerField(default=155000000000)),
                ('luxury_tax', models.BigIntegerField(default=189000000000)),
                ('apron', models.BigIntegerField(default=199000000000)),
                ('repeater_apron', models.BigIntegerField(default=209000000000)),
                ('mid_level', models.BigIntegerField(default=14000000000)),
                ('bi_annual', models.BigIntegerField(default=5000000000)),
                ('minimum_salary', models.BigIntegerField(default=2000000000)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'League Settings',
                'verbose_name_plural': 'League Settings',
            },
        ),
    ]
