# Generated by Django 6.0.3 on 2026-04-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_leaguesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='last_payroll_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='apron',
            field=models.BigIntegerField(default=199000000),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='bi_annual',
            field=models.BigIntegerField(default=5000000),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='luxury_tax',
            field=models.BigIntegerField(default=189000000),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='mid_level',
            field=models.BigIntegerField(default=14000000),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='minimum_salary',
            field=models.BigIntegerField(default=2000000),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='repeater_apron',
            field=models.BigIntegerField(default=209000000),
        ),
        migrations.AlterField(
            model_name='leaguesettings',
            name='salary_cap',
            field=models.BigIntegerField(default=155000000),
        ),
    ]
