# Generated by Django 6.0.3 on 2026-04-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_team_arena_renovation_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='arena_renovation_end',
        ),
        migrations.AddField(
            model_name='team',
            name='arena_renovation_cost',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='arena_renovation_days_left',
            field=models.IntegerField(default=0),
        ),
    ]
