# Generated by Django 6.0.3 on 2026-04-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_team_arena_renovation_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='arena_renovation_days_left',
        ),
        migrations.AddField(
            model_name='team',
            name='arena_renovation_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
