# Generated by Django 6.0.3 on 2026-04-04 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_team_arena_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.IntegerField(choices=[(1, 'Taquilla'), (2, 'Abonos'), (3, 'Patrocinios'), (4, 'Televisión'), (5, 'Remodelación'), (6, 'Despido')])),
                ('game_day', models.IntegerField(default=0)),
                ('amount', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_records', to='core.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_records', to='core.team')),
            ],
            options={
                'ordering': ['season', 'game_day', 'record_type'],
            },
        ),
        migrations.CreateModel(
            name='GameAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.IntegerField(default=0)),
                ('ticket_price', models.IntegerField(default=0)),
                ('revenue', models.BigIntegerField(default=0)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='core.game')),
            ],
        ),
        migrations.CreateModel(
            name='TeamSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_price', models.IntegerField(default=50)),
                ('subscription_price', models.IntegerField(default=2000)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fin_settings', to='core.team')),
            ],
        ),
    ]
