# Generated by Django 6.0.3 on 2026-04-04 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_message_game_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financerecord',
            name='created_at',
        ),
    ]
