# Generated by Django 6.0.3 on 2026-04-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_financerecord_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financerecord',
            name='record_type',
            field=models.IntegerField(choices=[(1, 'Taquilla'), (2, 'Abonos'), (3, 'Patrocinios'), (4, 'Televisión'), (5, 'Remodelación'), (6, 'Despido'), (7, 'Sueldos')]),
        ),
    ]
