# Generated by Django 6.0.3 on 2026-04-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_financerecord_record_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='game_mode',
            field=models.CharField(default='manager', max_length=20),
        ),
    ]
