# Generated by Django 6.0.3 on 2026-04-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_game_game_type_game_series_label_season_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_rookie',
            field=models.BooleanField(default=False),
        ),
    ]
