# Generated by Django 6.0.3 on 2026-04-08 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_finalsplayerstats_double_double_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_type', models.CharField(choices=[('points', 'Puntos'), ('rebounds', 'Rebotes'), ('assists', 'Asistencias'), ('steals', 'Robos'), ('blocks', 'Tapones'), ('fgm', 'Tiros de Campo'), ('fg3m', 'Triples'), ('ftm', 'Tiros Libres'), ('turnovers', 'Pérdidas')], db_index=True, max_length=20)),
                ('player_name', models.CharField(max_length=200)),
                ('value', models.IntegerField()),
                ('game_date', models.DateField()),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.team')),
            ],
            options={
                'ordering': ['stat_type', '-value'],
            },
        ),
    ]
