# Generated by Django 6.0.3 on 2026-04-08 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_type', models.CharField(choices=[('points', 'Puntos'), ('rebounds', 'Rebotes'), ('assists', 'Asistencias'), ('steals', 'Robos'), ('blocks', 'Tapones'), ('fgm', 'Tiros de Campo'), ('fg3m', 'Triples'), ('ftm', 'Tiros Libres'), ('turnovers', 'Pérdidas')], max_length=20, unique=True)),
                ('player_name', models.CharField(max_length=200)),
                ('value', models.IntegerField()),
                ('game_date', models.DateField()),
                ('team_abbreviation', models.CharField(max_length=3)),
            ],
            options={
                'ordering': ['stat_type'],
            },
        ),
        migrations.CreateModel(
            name='SeasonGameRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_type', models.CharField(choices=[('points', 'Puntos'), ('rebounds', 'Rebotes'), ('assists', 'Asistencias'), ('steals', 'Robos'), ('blocks', 'Tapones'), ('fgm', 'Tiros de Campo'), ('fg3m', 'Triples'), ('ftm', 'Tiros Libres'), ('turnovers', 'Pérdidas')], max_length=20)),
                ('player_name', models.CharField(max_length=200)),
                ('value', models.IntegerField()),
                ('game_date', models.DateField()),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_game_records', to='core.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_game_records', to='core.team')),
            ],
            options={
                'ordering': ['stat_type'],
                'unique_together': {('team', 'season', 'stat_type')},
            },
        ),
        migrations.CreateModel(
            name='TeamRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_type', models.CharField(choices=[('points', 'Puntos'), ('rebounds', 'Rebotes'), ('assists', 'Asistencias'), ('steals', 'Robos'), ('blocks', 'Tapones'), ('fgm', 'Tiros de Campo'), ('fg3m', 'Triples'), ('ftm', 'Tiros Libres'), ('turnovers', 'Pérdidas')], max_length=20)),
                ('player_name', models.CharField(max_length=200)),
                ('value', models.IntegerField()),
                ('game_date', models.DateField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_records', to='core.team')),
            ],
            options={
                'ordering': ['stat_type'],
                'unique_together': {('team', 'stat_type')},
            },
        ),
        migrations.DeleteModel(
            name='Record',
        ),
    ]
