# Generated by Django 6.0.3 on 2026-04-08 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_replace_record_with_three_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.CharField(max_length=100)),
                ('tier', models.CharField(choices=[('bronze', 'Bronce'), ('silver', 'Plata'), ('gold', 'Oro')], max_length=20)),
                ('initial_income', models.IntegerField()),
                ('home_game_income', models.IntegerField()),
                ('contract_years', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['tier', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TvChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.CharField(max_length=100)),
                ('tier', models.CharField(choices=[('bronze', 'Bronce'), ('silver', 'Plata'), ('gold', 'Oro')], max_length=20)),
                ('initial_income', models.IntegerField()),
                ('home_game_income', models.IntegerField()),
                ('contract_years', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['tier', 'name'],
            },
        ),
        migrations.AddField(
            model_name='teamsettings',
            name='sponsor_years_remaining',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamsettings',
            name='tv_years_remaining',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamsettings',
            name='sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sponsor'),
        ),
        migrations.AddField(
            model_name='teamsettings',
            name='tv_channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tvchannel'),
        ),
    ]
