# Generated by Django 6.0.3 on 2026-04-08 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_add_sponsors_tv'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponsor',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='tvchannel',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='tier',
        ),
        migrations.RemoveField(
            model_name='tvchannel',
            name='tier',
        ),
        migrations.AddField(
            model_name='sponsor',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tvchannel',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
