# Generated by Django 6.0.3 on 2026-03-30 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=5)),
                ('city', models.CharField(max_length=100)),
                ('conference', models.CharField(choices=[('East', 'Eastern Conference'), ('West', 'Western Conference')], max_length=10)),
                ('division', models.CharField(choices=[('Atlantic', 'Atlantic'), ('Central', 'Central'), ('Southeast', 'Southeast'), ('Northwest', 'Northwest'), ('Pacific', 'Pacific'), ('Southwest', 'Southwest')], max_length=20)),
                ('arena', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('owner', models.CharField(max_length=100)),
                ('attack', models.IntegerField(default=70)),
                ('defense', models.IntegerField(default=70)),
                ('overall', models.IntegerField(default=70)),
                ('budget', models.BigIntegerField(default=100000000)),
                ('reputation', models.IntegerField(default=3)),
                ('facilities', models.IntegerField(default=3)),
                ('logo', models.CharField(blank=True, max_length=200)),
                ('jersey_home', models.CharField(blank=True, max_length=200)),
                ('jersey_away', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('PG', 'Point Guard'), ('SG', 'Shooting Guard'), ('SF', 'Small Forward'), ('PF', 'Power Forward'), ('C', 'Center')], max_length=2)),
                ('age', models.IntegerField()),
                ('nationality', models.CharField(default='USA', max_length=100)),
                ('height_cm', models.IntegerField()),
                ('weight_kg', models.IntegerField()),
                ('overall', models.IntegerField(default=70)),
                ('potential', models.IntegerField(default=70)),
                ('speed', models.IntegerField(default=70)),
                ('shooting', models.IntegerField(default=70)),
                ('three_point', models.IntegerField(default=70)),
                ('passing', models.IntegerField(default=70)),
                ('ball_handling', models.IntegerField(default=70)),
                ('defense', models.IntegerField(default=70)),
                ('rebounding', models.IntegerField(default=70)),
                ('athleticism', models.IntegerField(default=70)),
                ('iq', models.IntegerField(default=70)),
                ('salary', models.IntegerField(default=5000000)),
                ('contract_years', models.IntegerField(default=2)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='core.team')),
            ],
            options={
                'ordering': ['-overall'],
            },
        ),
    ]
