# Generated by Django 6.0.3 on 2026-04-01 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_start', models.IntegerField()),
                ('year_end', models.IntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('current_game_day', models.IntegerField(default=0)),
                ('generated', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-year_start'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_day', models.IntegerField()),
                ('game_date', models.DateField()),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('is_played', models.BooleanField(default=False)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_games', to='core.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_games', to='core.team')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='core.season')),
            ],
            options={
                'ordering': ['season', 'game_day', 'pk'],
                'unique_together': {('season', 'home_team', 'away_team', 'game_day')},
            },
        ),
    ]
