# Generated by Django 6.0.3 on 2026-04-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_game_q1_away_game_q1_home_game_q2_away_game_q2_home_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='morale',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='manager',
            name='pressure',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='manager',
            name='trust',
            field=models.IntegerField(default=50),
        ),
    ]
