# Generated by Django 6.0.3 on 2026-04-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_manager_morale_manager_pressure_manager_trust'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergamestats',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
