# Generated by Django 6.0.3 on 2026-04-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_playergamestats_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='blocks',
            field=models.IntegerField(default=70),
        ),
        migrations.AddField(
            model_name='player',
            name='steals',
            field=models.IntegerField(default=70),
        ),
    ]
