# Generated by Django 6.0.3 on 2026-04-02 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='game_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
