# Generated by Django 6.0.3 on 2026-04-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_message_game_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='injury_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='injury_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
