# Generated by Django 6.0.3 on 2026-04-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_season_last_payroll_month_alter_leaguesettings_apron_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=2)),
                ('overall', models.IntegerField(default=70)),
                ('team_name', models.CharField(default='', max_length=100)),
                ('team_abbreviation', models.CharField(default='', max_length=5)),
                ('team_logo', models.CharField(blank=True, default='', max_length=200)),
                ('games', models.IntegerField(default=0)),
                ('total_points', models.IntegerField(default=0)),
                ('total_rebounds', models.IntegerField(default=0)),
                ('total_assists', models.IntegerField(default=0)),
                ('total_steals', models.IntegerField(default=0)),
                ('total_blocks', models.IntegerField(default=0)),
                ('total_fgm', models.IntegerField(default=0)),
                ('total_fga', models.IntegerField(default=0)),
                ('total_fg3m', models.IntegerField(default=0)),
                ('total_fg3a', models.IntegerField(default=0)),
                ('total_ftm', models.IntegerField(default=0)),
                ('total_fta', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-total_points'],
                'unique_together': {('first_name', 'last_name')},
            },
        ),
    ]
