# Generated by Django 6.0.3 on 2026-04-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_historicalplayerstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalplayerstats',
            name='total_turnovers',
            field=models.IntegerField(default=0),
        ),
    ]
