# Generated by Django 6.0.3 on 2026-04-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_historicalplayerstats_total_turnovers'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='arena_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='team',
            name='arena_renovation_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='arena_renovation_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
