# Generated by Django 6.0.3 on 2026-04-03 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_team_arena_level_team_arena_renovation_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='arena_level',
        ),
    ]
