# Generated by Django 6.0.3 on 2026-04-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_team_arena_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='arena_renovation_count',
            field=models.IntegerField(default=0),
        ),
    ]
