# Generated by Django 6.0.3 on 2026-04-03 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_team_arena_renovation_days_left_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='arena_renovation_end_date',
        ),
        migrations.AddField(
            model_name='team',
            name='arena_renovation_end_day',
            field=models.IntegerField(default=0),
        ),
    ]
