# Generated by Django 6.0.3 on 2026-04-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_team_arena_renovation_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='arena_image',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
