# Generated by Django 6.0.3 on 2026-04-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_financerecord_gameattendance_teamsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='game_day',
            field=models.IntegerField(default=0),
        ),
    ]
