# Generated by Django 6.0.3 on 2026-04-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_season_game_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('regular', 'Regular Season'), ('playin', 'Play-In'), ('playoff', 'Playoffs')], default='regular', max_length=10),
        ),
        migrations.AddField(
            model_name='game',
            name='series_label',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='season',
            name='phase',
            field=models.CharField(choices=[('regular', 'Regular Season'), ('playin', 'Play-In'), ('playoffs', 'Playoffs'), ('finished', 'Temporada Finalizada')], default='regular', max_length=10),
        ),
    ]
