# Generated by Django 6.0.3 on 2026-04-07 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_finalsplayerstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finals_result', models.CharField(default='', max_length=10)),
                ('season_mvp_rating', models.FloatField(blank=True, null=True)),
                ('season_mvp_games', models.IntegerField(blank=True, null=True)),
                ('rookie_rating', models.FloatField(blank=True, null=True)),
                ('rookie_games', models.IntegerField(blank=True, null=True)),
                ('champion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='championships', to='core.team')),
                ('finalist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalist_appearances', to='core.team')),
                ('finals_mvp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finals_mvps', to='core.player')),
                ('rookie_of_year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rookie_awards', to='core.player')),
                ('season', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='record', to='core.season')),
                ('season_mvp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='season_mvps', to='core.player')),
            ],
            options={
                'ordering': ['-season__year_start'],
            },
        ),
    ]
