# Generated by Django 6.0.3 on 2026-04-07 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_seasonrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonrecord',
            name='all_star_c',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='all_star_c_seasons', to='core.player'),
        ),
        migrations.AddField(
            model_name='seasonrecord',
            name='all_star_pf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='all_star_pf_seasons', to='core.player'),
        ),
        migrations.AddField(
            model_name='seasonrecord',
            name='all_star_pg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='all_star_pg_seasons', to='core.player'),
        ),
        migrations.AddField(
            model_name='seasonrecord',
            name='all_star_sf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='all_star_sf_seasons', to='core.player'),
        ),
        migrations.AddField(
            model_name='seasonrecord',
            name='all_star_sg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='all_star_sg_seasons', to='core.player'),
        ),
    ]
