# Generated by Django 6.0.3 on 2026-04-07 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_seasonrecord_all_star_c_seasonrecord_all_star_pf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_retired',
            field=models.BooleanField(default=False),
        ),
    ]
