# Generated by Django 6.0.3 on 2026-04-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_player_is_retired'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalsplayerstats',
            name='double_double',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='finalsplayerstats',
            name='triple_double',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalplayerstats',
            name='total_double_doubles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalplayerstats',
            name='total_triple_doubles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playergamestats',
            name='double_double',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playergamestats',
            name='triple_double',
            field=models.IntegerField(default=0),
        ),
    ]
